### PR TITLE
add a vcenter_copy command

### PR DESCRIPTION
**Pull request by chrismeyersfsu**
- More modular design. Makes understanding the set of parameters easy.

### CODE REVIEW

**Comment by whereismyjetpack** [comment]
Hi. thanks for this PR. I have not had the chance to test yet -- but didn't want you to think I forgot about this.

**Comment by chrismeyersfsu** [comment]
ping

**Comment by chrismeyersfsu** [comment]
PING

**Comment by whereismyjetpack** [comment]
Apologies for the delay. I'm still bouncing around the idea of breaking the larger vCenter module as a whole into smaller modules, or just adding the copy command to the current vCenter module. just adding copy probably would have been faster for me to test / merge in, sorry again for the delay -- is there a dire need to have this merged into my repo?

**Comment by chrismeyersfsu** [comment]
Not really a need. I was trying to push the module interface to be more like other Ansible cloudy interfaces in hopes of it getting pushed into core.

**Comment by whereismyjetpack** [comment]
Agreed. I tried to get interest from the developer  community before writing this module, and no one seemed to want to move from pysphere to pyvmomi. We needed features of pyvmomi so we built vcenter to differentiate from vsphere_guest 

Some day when I get some free time, I may break these functions into modular components, vcenter_clone, vcenter_reconfigure etc.

**Comment by chrismeyersfsu** [comment]
@whereismyjetpack There is interest at Ansible of doing just that (breaking the modules in components and using pyvmomi over vcenter). As a first step, can you add a license (ansible is gplv3) to this repo?

**Comment by whereismyjetpack** [comment]
I had some time to look at this today, I like the idea of breaking up the module into sub modules, but am not willing to do so at this time, a lot of boilerplate code would need to be copied to each and every submodule until ansible supports multi-file custom modules. since I don't anticipate this getting merged into ansible, functions like 'find_vm' and the boilerplate used to connect to a vcenter server would need to be copied and pasted everywhere. I'm going to leave this as a single file and watch the progress of custom modules within ansible.

**Pull request closed without merging**
